data_source:
    url: "https://raw.githubusercontent.com/jmem-ec/KRRCourse/ccbd6ccf8389ba0988d53fc9300a64da00e6368b/Consignment_pricing.csv"
    external_data_dir: "data/external"
    filename: "Consignment_pricing.csv"
